import { Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  [Language.English]: {
    greeting: "Welcome to SaloonSoft! How can I assist you today?",
    languagePrompt: "Please select your preferred language:",
    mainMenuPrompt: "Please choose an option:",
    appointment: "Appointment",
    billing: "Billing",
    configuration: "Configuration",
    keyFeatures: "Key Features",
    stepByStep: "Step-by-Step Process",
    troubleshooting: "Troubleshooting",
    faqs: "FAQs",
    backToMainMenu: "Back to Main Menu",
    subMenuPrompt: "You've selected {module}. Please choose an option:",
    confirmation: "You selected: {option}. Here is the information:",
    noData: "Sorry, we couldn't find information for this topic. Please try another option.",
    askRestart: "Would you like to go back to the Main Menu or Exit?",
    exit: "Exit",
    thankYou: "Thank you for using SaloonSoft Assistant. Have a great day!",
  },
  [Language.Hindi]: {
    greeting: "सैलूनसॉफ्ट में आपका स्वागत है! मैं आज आपकी कैसे सहायता कर सकता हूँ?",
    languagePrompt: "कृपया अपनी पसंदीदा भाषा चुनें:",
    mainMenuPrompt: "कृपया एक विकल्प चुनें:",
    appointment: "अपॉइंटमेंट",
    billing: "बिलिंग",
    configuration: "कॉन्फ़िगरेशन",
    keyFeatures: "मुख्य विशेषताएँ",
    stepByStep: "चरण-दर-चरण प्रक्रिया",
    troubleshooting: "समस्या निवारण",
    faqs: "अक्सर पूछे जाने वाले प्रश्न",
    backToMainMenu: "मुख्य मेनू पर वापस जाएं",
    subMenuPrompt: "आपने {module} चुना है। कृपया एक विकल्प चुनें:",
    confirmation: "आपने चुना: {option}। यहाँ जानकारी है:",
    noData: "क्षमा करें, हमें इस विषय के लिए जानकारी नहीं मिली। कृपया दूसरा विकल्प आज़माएँ।",
    askRestart: "क्या आप मुख्य मेनू पर वापस जाना चाहेंगे या बाहर निकलना चाहेंगे?",
    exit: "बाहर निकलें",
    thankYou: "सैलूनसॉफ्ट असिस्टेंट का उपयोग करने के लिए धन्यवाद। आपका दिन शुभ हो!",
  },
  [Language.Gujarati]: {
    greeting: "સલૂનસોફ્ટમાં આપનું સ્વાગત છે! હું આજે તમારી કેવી રીતે મદદ કરી શકું?",
    languagePrompt: "કૃપા કરીને તમારી પસંદગીની ભાષા પસંદ કરો:",
    mainMenuPrompt: "કૃપા કરીને એક વિકલ્પ પસંદ કરો:",
    appointment: "એપોઇન્ટમેન્ટ",
    billing: "બિલિંગ",
    configuration: "કન્ફિગરેશન",
    keyFeatures: "મુખ્ય વિશેષતાઓ",
    stepByStep: "પગલા-દર-પગલાની પ્રક્રિયા",
    troubleshooting: "મુશ્કેલીનિવારણ",
    faqs: "વારંવાર પૂછાતા પ્રશ્નો",
    backToMainMenu: "મુખ્ય મેનુ પર પાછા જાઓ",
    subMenuPrompt: "તમે {module} પસંદ કર્યું છે. કૃપા કરીને એક વિકલ્પ પસંદ કરો:",
    confirmation: "તમે પસંદ કર્યું: {option}. અહીં માહિતી છે:",
    noData: "માફ કરશો, અમને આ વિષય માટે માહિતી મળી નથી. કૃપા કરીને બીજો વિકલ્પ અજમાવો.",
    askRestart: "શું તમે મુખ્ય મેનુ પર પાછા જવા માંગો છો કે બહાર નીકળવા માંગો છો?",
    exit: "બહાર નીકળો",
    thankYou: "સલૂનસોફ્ટ આસિસ્ટન્ટનો ઉપયોગ કરવા બદલ આભાર. તમારો દિવસ સારો રહે!",
  }
};
